INICIO DE DIAGRAMAS IEA

In [ ]:
import numpy as np
import pandas as pd

In [21]:
import os
file_path = 'Electricity generation by source - Colombia.csv'
if not os.path.exists(file_path):
	print(f"The file '{file_path}' does not exist in the current directory: {os.getcwd()}")
	print(f"Absolute path to check: {os.path.abspath(file_path)}")
	raise FileNotFoundError(f"The file '{file_path}' does not exist. Please ensure it is in the correct directory.")

Data = pd.read_csv(file_path)
Data.head()

,Country,year,Coal,Oil,Natural gas,Biofuels,Hydro,Solar PV,Wind,Other sources,Units
0,NaN,1990,3708,379,4499,274,27497,NaN,NaN,NaN,GWh
1,NaN,1991,3803,406,4786,269,27726,NaN,NaN,NaN,GWh
2,NaN,1992,4669,713,4941,340,22281,NaN,NaN,NaN,GWh
3,NaN,1993,4350,518,5445,389,27857,NaN,NaN,NaN,GWh
4,NaN,1994,3541,418,4947,444,32059,NaN,NaN,NaN,GWh

In [22]:
Data = Data.drop(columns=['Coal','Oil', 'Natural gas'])

IMPORTAR DIAGRAMAS

In [23]:
Data['Country'] = 'Colombia'

Grupos = Data.groupby('Country')
EnergyCol = Grupos.get_group('Colombia')
EnergyCol

     Country  year  Biofuels  Hydro  Solar PV   Wind  Other sources Units
0   Colombia  1990       274  27497       NaN    NaN            NaN   GWh
1   Colombia  1991       269  27726       NaN    NaN            NaN   GWh
2   Colombia  1992       340  22281       NaN    NaN            NaN   GWh
3   Colombia  1993       389  27857       NaN    NaN            NaN   GWh
4   Colombia  1994       444  32059       NaN    NaN            NaN   GWh
5   Colombia  1995       477  32160       NaN    NaN            NaN   GWh
6   Colombia  1996       496  35491       NaN    NaN            NaN   GWh
7   Colombia  1997       483  31474       NaN    NaN            NaN   GWh
8   Colombia  1998       532  30782       NaN    NaN            NaN   GWh
9   Colombia  1999       457  33741       NaN    NaN            NaN   GWh
10  Colombia  2000       496  32074       6.0    NaN            NaN   GWh
11  Colombia  2001       496  31798       6.0    NaN            NaN   GWh
12  Colombia  2002       491  33968       6.0    NaN            NaN   GWh
13  Colombia  2003       495  36174       6.0    NaN            NaN   GWh
14  Colombia  2004       467  40077       7.0   52.0            NaN   GWh
15  Colombia  2005       503  39803       7.0   49.0            NaN   GWh
16  Colombia  2006       530  42742       7.0   63.0            NaN   GWh
17  Colombia  2007       532  44445       7.0   50.0            NaN   GWh
18  Colombia  2008       537  46403       7.0   54.0            NaN   GWh
19  Colombia  2009       541  41050       7.0   58.0            NaN   GWh
20  Colombia  2010      2417  40401       8.0   39.0            NaN   GWh
21  Colombia  2011      1999  48878       8.0   41.0            NaN   GWh
22  Colombia  2012      1953  47582       8.0   55.0            NaN   GWh
23  Colombia  2013      1048  50260       8.0   58.0            NaN   GWh
24  Colombia  2014      1347  47870       9.0   70.0            NaN   GWh
25  Colombia  2015      1371  48568       9.0   68.0            NaN   GWh
26  Colombia  2016      1462  49096       9.0   51.0            NaN   GWh
27  Colombia  2017      1427  61434      14.0    3.0            NaN   GWh
28  Colombia  2018      1457  59932      20.0   43.0            NaN   GWh
29  Colombia  2019      1569  54593     136.0   63.0            NaN   GWh
30  Colombia  2020      2148  49977     200.0   10.0            NaN   GWh
31  Colombia  2021      2243  62318     332.0   62.0          821.0   GWh
32  Colombia  2022      2340  62248     517.0   74.0           12.0   GWh
33  Colombia  2023      2340  57244     963.0  111.0           12.0   GWh

DIAGRAMAS

In [ ]:
import matplotlib.pyplot as plt

DIAGRAMA DE LINEAS

In [ ]:
DataAll = EnergyCol[['Biofuels','Hydro','Solar PV','Wind','Other sources']]
plt.plot(EnergyCol['year'], DataAll, label=DataAll.columns)
plt.title('Electricity generation by source - Colombia')
plt.xlabel('Años')
plt.ylabel('Electricity generation (GWh)')
plt.legend(DataAll.columns, loc='upper left')
plt.grid()
plt.show()

In [ ]:
Total_Energia = np.sum(EnergyCol.select_dtypes(include='number'))
Total_Energia = Total_Energia.iloc[1:]
Total_Energia

In [ ]:
Total_Energia

DIAGRAMA DE BARRAS

In [ ]:
plt.figure(figsize=(10, 5))
plt.bar(Total_Energia.index, Total_Energia.values , color=['aquamarine', 'green', 'grey', 'blue', 'orange'])
plt.title('Electricity generation by source - Colombia')
plt.xlabel('Años')
plt.ylabel('Electricity generation (GWh)')
plt.xticks(rotation=45)

DIAGRAMA DE BARRAS INDIVIDUAL

In [ ]:
plt.hist(DataAll['Hydro'], bins=7, color='blue', alpha=0.7, label='Hydro', edgecolor='black')
plt.title('Electricity generation by source - Colombia')
plt.xlabel('Hydro generation (GWh)')
plt.ylabel('Frequency')
plt.show()

In [ ]:
plt.hist(DataAll['Biofuels'], bins=7, color='Green', alpha=0.7, label='Biofuels', edgecolor='black')
plt.title('Electricity generation by source - Colombia')
plt.xlabel('Biofuels generation (GWh)')
plt.ylabel('Frequency')
plt.show()

In [ ]:
plt.hist(DataAll['Solar PV'], bins=7, color='Yellow', alpha=0.7, label='Solar PV', edgecolor='black')
plt.title('Electricity generation by source - Colombia')
plt.xlabel('Solar PV generation (GWh)')
plt.ylabel('Frequency')
plt.show()

In [ ]:
plt.hist(DataAll['Wind'], bins=7, color='Grey', alpha=0.7, label='Wind', edgecolor='black')
plt.title('Electricity generation by source - Colombia')
plt.xlabel('Wind generation (GWh)')
plt.ylabel('Frequency')
plt.show()

In [ ]:
plt.hist(DataAll['Other sources'], bins=7, color='Black', alpha=0.7, label='Other sources', edgecolor='black')
plt.title('Electricity generation by source - Colombia')
plt.xlabel('Other sources generation (GWh)')
plt.ylabel('Frequency')
plt.show()

In [ ]:
fig, ax = plt.subplots(2,3, figsize=(15,15), dpi=80, facecolor='w', edgecolor='k')
ax[0,0].hist(DataAll['Hydro'], bins=7, color='blue', alpha=0.7, label='Hydro', edgecolor='black')
ax[0,0].set_title('Electricity generation by source - Colombia')
ax[0,0].set_xlabel('Hydro generation (GWh)')
ax[0,0].set_ylabel('Frequency')
ax[0,0].grid()
ax[0,1].hist(DataAll['Biofuels'], bins=7, color='Green', alpha=0.7, label='Biofuels', edgecolor='black')
ax[0,1].set_title('Electricity generation by source - Colombia')
ax[0,1].set_xlabel('Biofuels generation (GWh)')
ax[0,1].set_ylabel('Frequency')
ax[0,1].grid()
ax[0,2].hist(DataAll['Solar PV'], bins=7, color='Yellow', alpha=0.7, label='Solar PV', edgecolor='black')
ax[0,2].set_title('Electricity generation by source - Colombia')
ax[0,2].set_xlabel('Solar PV generation (GWh)')
ax[0,2].set_ylabel('Frequency')
ax[0,2].grid()
ax[1,0].hist(DataAll['Wind'], bins=7, color='Grey', alpha=0.7, label='Wind', edgecolor='black')
ax[1,0].set_title('Electricity generation by source - Colombia')
ax[1,0].set_xlabel('Wind generation (GWh)')
ax[1,0].set_ylabel('Frequency')
ax[1,0].grid()
ax[1,1].hist(DataAll['Other sources'], bins=7, color='Black', alpha=0.7, label='Other sources', edgecolor='black')
ax[1,1].set_title('Electricity generation by source - Colombia')
ax[1,1].set_xlabel('Other sources generation (GWh)')
ax[1,1].set_ylabel('Frequency')
ax[1,1].grid()
ax[1,2].axis('off')
plt.show()

DIAGRAMA DE PASTEL

In [ ]:
Energias = ['Biofuels', 'Hydro', 'Solar PV', 'Wind', 'Other sources']
Filtered_Total_Energia = Total_Energia[Energias]  # Filter Total_Energia to match Energias
plt.pie(Filtered_Total_Energia, labels=Energias, autopct='%1.1f%%', startangle=50, colors=['pink', 'blue', 'yellow', 'grey', 'black'], explode=(0.05, 0.10, 0.20, 0.25, 0.30), shadow=True, radius=1.2)
plt.title("Distribución de energía por fuente", fontsize=25, color='black', loc='center', pad=20)
plt.axis('equal')
plt.legend(loc='upper left', fontsize=10, title='Fuentes de energía', title_fontsize='13', shadow=True, facecolor='white', edgecolor='black')
plt.grid()
plt.show()